<a href="https://colab.research.google.com/github/singhm9283-bot/K-NN-/blob/main/K_NNJune_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

uploaded = files.upload()

Saving Fish.csv to Fish.csv

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('Fish.csv')

In [4]:
df.describe()

            Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

In [5]:
df['Weight'].skew()

np.float64(1.1044503929261893)

In [6]:
df['Weight'] = df['Weight'].replace(0, np.nan)

df['Weight'] = df['Weight'].fillna(df['Weight'].median())

In [7]:
df['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [8]:
df.describe()

            Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    400.096855   26.247170   28.415723   31.227044    8.970994    4.417486
std     356.689642    9.996441   10.716328   11.610246    4.286208    1.685804
min       5.900000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     122.500000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     281.500000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

In [9]:
X = df.drop('Species', axis = 1)

X.head()

   Weight  Length1  Length2  Length3   Height   Width
0   242.0     23.2     25.4     30.0  11.5200  4.0200
1   290.0     24.0     26.3     31.2  12.4800  4.3056
2   340.0     23.9     26.5     31.1  12.3778  4.6961
3   363.0     26.3     29.0     33.5  12.7300  4.4555
4   430.0     26.5     29.0     34.0  12.4440  5.1340

In [10]:
y = df['Species']

y.head()

0    Bream
1    Bream
2    Bream
3    Bream
4    Bream
Name: Species, dtype: object

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [13]:
accuracy_list = []

In [14]:
for i in range(1, 11):

  knn = KNeighborsClassifier(n_neighbors = i)

  knn.fit(X_train, y_train)

  # Finding the Predicted Values of the KNN Model

  y_prediction = knn.predict(X_test)

  # Finding the Accuracy

  acs = accuracy_score(y_test, y_prediction)

  # Adding the Accuracy Score to the List

  accuracy_list.append(acs)

NameError: name 'accuracy_score' is not defined

In [ ]:
plt.plot(range(1, 11), accuracy_list, marker = 'o')

plt.xlabel('Value of K')
plt.ylabel('Accuracy')
plt.title('Elbow Method for K-NN: Value of K vs. Accuracy')
plt.grid()

plt.show()